apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testpage-claim
  namespace: testpage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

