apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: wp
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/media/kubestor01/wordpress-www/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-claim
  namespace: wp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: wp
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: "10Gi"
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: "/media/kubestor01/wordpress-www/wp"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-claim
  namespace: wp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi