apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: valheim-server
    meta.helm.sh/release-namespace: valheim
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: microk8s.io/hostpath
    volume.kubernetes.io/selected-node: k8s-dev-master
    volume.kubernetes.io/storage-provisioner: microk8s.io/hostpath
  creationTimestamp: "2023-09-15T14:30:40Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: valheim-server-server-base-data
  namespace: valheim
  resourceVersion: "141100"
  uid: b813331e-e624-4e42-921e-03c0d6d6fea8
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  volumeName: pvc-b813331e-e624-4e42-921e-03c0d6d6fea8
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  phase: Bound
