apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: valheim-server
    meta.helm.sh/release-namespace: valheim
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: microk8s.io/hostpath
    volume.kubernetes.io/selected-node: k8s-dev-master
    volume.kubernetes.io/storage-provisioner: microk8s.io/hostpath
  creationTimestamp: "2023-09-15T14:30:40Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/managed-by: Helm
  name: valheim-server-world-data
  namespace: valheim
  resourceVersion: "141103"
  uid: 13de877f-fe10-4b64-ac67-d19cd241a4d2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  volumeName: pvc-13de877f-fe10-4b64-ac67-d19cd241a4d2
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  phase: Bound
